name: Publish Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - uses: actions/cache@v3
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}

    - name: Set Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
        dir: streamlit_ydata_profiling/frontend

    - name: Run build
      uses: borales/actions-yarn@v4
      with:
        cmd: build # will run `yarn build` command
        dir: streamlit_ydata_profiling/frontend

    - name: Install hatch
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Configure poetry
      run: python -m poetry config virtualenvs.create false
    - name: Install dependencies
      run: |
        poetry install
    - name: Publish
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry config pypi-token.pypi $PYPI_TOKEN
        poetry publish --build
